### PR TITLE
[enh] locales: make server name a variable

### PR DESCRIPTION
**Pull request by tituspijean**
Enables translation into languages that do not put the server name at the end of the sentence.

@LittleGolden, can you test it out?

### CODE REVIEW

**Comment by Littlegolden** [comment]
Okey, I'll test this now~

**Comment by Littlegolden** [comment]
You forgot this line~

https://github.com/tituspijean/flarum-ext-auth-ldap/blob/ee33d7aaa27f078e9f00810d4441ce22180bc393/js/src/forum/components/LDAPLogInModal.js#L44

>>
```
    return app.translator.trans(translationPrefix + 'log_in_with', {server: app.forum.attribute('LDAP_method_name')});
```

**Comment by tituspijean** [comment]
Thanks, nice catch! What do you think now?

**Review by Littlegolden — APPROVED** [review]
NICE

**Pull request merged**
